name = "life-plan"
main = "worker/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "life-plan-license"
database_id = "911ca7c6-6c00-4c98-ac87-f701d9a7d6b9"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
