name = "life-plan"
main = "worker/preview.js"
compatibility_date = "2025-01-01"
workers_dev = true
preview_urls = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
